export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO';
export const MOSTRAR_FORMULARIO = 'MOSTRAR_FORMULARIO';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const OBTENER_MANAGERS = 'OBTENER_MANAGERS';
export const OBTENER_ASIGNADOS = 'OBTENER_ASIGNADOS';
export const PAGINA_ACTUAL = 'PAGINA_ACTUAL';


